"""DwsAdapter 子系统 mixin 共享基类（F9 类型治理）。

共享基类仅做类型声明（方法裸参数 stub + 状态 Any），集中声明跨 mixin 交叉
成员；无 __init__、无方法体，运行时代入 MRO 由组合类/各 mixin 真实赋值与实现，
零行为影响。惰性注解，运行时仅依赖 LinkoraComponentBase（无循环导入）。
"""
from __future__ import annotations

from typing import Any

from src.im_adapter.base_adapter import BaseIMAdapter


class DwsAdapterBase(BaseIMAdapter):
    # === 内部状态（组合类 / 各 mixin __init__ 赋值；精确类型见赋值点） ===
    _dws_config_dir: Any
    _list_all_cap_warn_at: Any
    _perm_warned: Any
    ai_tag_default: Any
    _disable_bot_fallback: bool

    # === 跨 mixin 方法（真实签名原样；实现在各自 mixin） ===
    def _base_error_class(self) -> Any: ...
    def _build_command(self, args, *, force_no_dry_run) -> Any: ...
    def _chat_message_list_all_single(self, start, end, limit, timeout, max_pages) -> Any: ...
    def _chat_message_list_all_windowed(self, start_dt, end_dt, limit, timeout, max_pages, window_days) -> Any: ...
    def _classify_error(self, error_msg) -> Any: ...
    @staticmethod
    def _extract_media_id(data) -> Any: ...
    def _get_current_profile_local(self) -> Any: ...
    def _get_result(self, data) -> Any: ...
    def _infer_single_chat(self, chat) -> Any: ...
    def _is_benign_error(self, error_msg) -> Any: ...
    def _is_personal_dingtalk_error(self, err_str) -> Any: ...
    def _make_no_browser_env(self) -> Any: ...
    @staticmethod
    def _merge_list_all_conversations(merged, convs) -> Any: ...
    def _minutes_get(self, sub, minutes_id) -> Any: ...
    def _non_retryable_error_class(self) -> Any: ...
    def _permission_error_class(self) -> Any: ...
    def _read_local_profiles(self) -> Any: ...
    def _retryable_error_class(self) -> Any: ...
    def auth_login(self, device_flow, no_browser) -> Any: ...
    def auth_status(self) -> Any: ...
    def calendar_event_list(self, start, end) -> Any: ...
    def chat_conversation_info(self, chat_id) -> Any: ...
    def chat_list_top_conversations(self, limit) -> Any: ...
    def chat_message_list(self, group, time_str, limit, cached_result, timeout) -> Any: ...
    def chat_message_list_all(self, start, end, limit, timeout, extra_chat_ids, chat_ids, chat_meta, max_pages, window_days) -> Any: ...
    def chat_message_list_direct(self, user_id, open_dingtalk_id, time_str, limit) -> Any: ...
    def chat_message_list_unread_conversations(self, count) -> Any: ...
    def chat_message_reply(self, *, message_id, text, title, uuid, reply_in_thread, group, user, open_dingtalk_id, msg_type, media_id, file_path, ref_msg_id, ref_sender, conversation_id, use_native_reply, fallback_to_send) -> Any: ...
    def chat_message_send(self, *, group, user, open_dingtalk_id, title, text, uuid, ai_tag, msg_type, media_id, file_path, at_all, at_open_dingtalk_ids) -> Any: ...
    def chat_message_update(self, *, message_id, text, title, group, user) -> Any: ...
    def contact_user_get_self(self, timeout) -> Any: ...
    def contact_user_search(self, keyword) -> Any: ...
    def doc_read(self, node_id, content_format) -> Any: ...
    def doc_search(self, query, page_size) -> Any: ...
    def download_media(self, *, media_id, message_id, conversation_id, output_path) -> Any: ...
    def get_current_org(self) -> Any: ...
    def is_authenticated(self) -> Any: ...
    def list_orgs(self) -> Any: ...
    def mark_read(self, conversation_id, message_id) -> Any: ...
    def media_upload(self, file_path, media_type) -> Any: ...
    def minutes_get_info(self, minutes_id) -> Any: ...
    def minutes_get_summary(self, minutes_id) -> Any: ...
    def minutes_get_todos(self, minutes_id) -> Any: ...
    def minutes_get_transcription(self, minutes_id) -> Any: ...
    def minutes_list(self, scope, query, start, end, limit, cursor) -> Any: ...
    def oa_approval_detail(self, instance_id) -> Any: ...
    def oa_approval_list_executed(self, page, limit, query) -> Any: ...
    def oa_approval_list_forms(self, cursor, limit) -> Any: ...
    def oa_approval_list_initiated(self, process_code, start, end, cursor, limit) -> Any: ...
    def oa_approval_list_pending(self, start, end, query, page, limit) -> Any: ...
    def oa_approval_redirect_task(self, *, task_id, to_actioner_id, remark) -> Any: ...
    def oa_approval_search_forms(self, query) -> Any: ...
    def oa_approval_tasks(self, instance_id) -> Any: ...
    def profile_list(self) -> Any: ...
    def todo_task_create(self, title, executors, due, priority) -> Any: ...
    def use_org(self, corp_id) -> Any: ...
    def wiki_node_list(self, workspace_id, folder, limit, cursor) -> Any: ...
    def wiki_node_search(self, workspace_id, query, extensions, limit, cursor) -> Any: ...
    def wiki_space_list(self, space_type, limit, cursor) -> Any: ...
    def wiki_space_search(self, query, space_type, limit) -> Any: ...
