"""Platform/Engine 子系统 mixin 共享基类（F9 类型治理）。

LinkoraEngine 由 5 个顶层 mixin（Primary/Runtime/MessageLoop/Memory/Lifecycle）
经多继承组合，Runtime 又聚合 7 个运行时子 mixin。这些 mixin 交叉访问彼此的
状态（self._xxx）与方法（self._xxx()），pyright 逐文件静态分析时 self 只认
当前 mixin，故报 unknown attribute。

本类作为所有 platform mixin 的共同祖先，集中声明这些交叉成员：
- 状态：实例属性注解（无值，组合类 / 各 mixin __init__ 赋值）。内部状态统一用
  Any，因为各属性在赋值点已声明精确类型，基类用 Any 既能消解跨 mixin 访问的
  unknown-attribute 报错，又不会与赋值点的真实类型冲突。
- 方法：以「真实实现的完整签名」原样声明（非 *args/**kwargs），避免与子类
  实现的具体签名触发 reportIncompatibleMethodOverride。

惰性注解 + TYPE_CHECKING 导入，运行时零 import、零 MRO 风险。
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any

from src.component_base import LinkoraComponentBase

if TYPE_CHECKING:
    from src.config import AppConfig
    from src.dws_adapter import DwsAdapter
    from src.llm.agent import LLMAgent
    from src.memory.sqlite_store import SQLiteStore
    from src.poller import MessagePoller


class EngineMixinBase(LinkoraComponentBase):
    # === 精确类型共享状态（组合类 __init__ 赋值） ===
    config: AppConfig
    store: SQLiteStore
    dws: DwsAdapter
    poller: MessagePoller
    llm_agent: LLMAgent

    # === engine 内部状态（组合类 / 各 mixin __init__ 赋值；精确类型见赋值点） ===
    _INCOMPLETE_REQUEST_VERBS: Any
    _INCOMPLETE_STRUCT_RE: Any
    _backoff_cleanup_counter: Any
    _bg_threads: Any
    _bg_throttle: Any
    _incomplete_delay_count: Any
    _incomplete_extra_sec: Any
    _incomplete_fired_with_request: Any
    _incomplete_fired_without_request: Any
    _last_extract_time: Any
    _last_extract_time_lock: Any
    _last_reply_send_ts: Any
    _memory_executor: Any
    _metrics_lock: Any
    _module_reloader: Any
    _owner_open_dingtalk_id: Any
    _pending_first_seen: Any
    _pending_incomplete_wait: Any
    _pending_messages: Any
    _pending_platform: Any
    _pending_timers: Any
    _reply_lock_retries: Any
    _reply_rate_limited_until: Any
    _reply_send_throttle_lock: Any
    _replying_chats: Any
    _replying_lock: Any
    _replying_since: Any
    _running: Any
    _send_backoff_until: Any
    _shutdown_event: Any
    _skill_manager: Any
    _timer_lock: Any
    _tool_whitelist_drift: Any
    config_path: Any
    current_open_dingtalk_id: Any
    current_user_dept: Any
    current_user_org: Any
    current_user_title: Any
    db_backup: Any
    db_backups: Any
    doc_sync_scheduler: Any
    embedding_client: Any
    llm_client: Any
    platforms: Any
    rule_engine: Any
    tool_router: Any

    # === 跨 mixin 方法（真实签名原样；实现在各自 mixin） ===
    # 注意：绝不声明 __init__ —— 会在 MRO 中截胡真实初始化链，
    # 使 InboundMixin() 等无参实例化直接抛 TypeError
    @property
    def _active_ctx(self) -> Any: ...
    def _append_citation_footer(self, text, reply, message) -> Any: ...
    def _apply_rule_result(self, message, result) -> Any: ...
    def _auto_save_memory(self, user_msg, ai_reply, history) -> Any: ...
    def _batch_has_request(self, messages) -> Any: ...
    def _batch_has_structured_data(self, messages) -> Any: ...
    def _build_adapter(self, pcfg) -> Any: ...
    def _build_dws(self) -> Any: ...
    def _build_platform_context(self, pcfg) -> Any: ...
    def _build_tool_services(self, self_id) -> Any: ...
    def _cleanup_backoff(self) -> Any: ...
    def _compute_debounce_delay(self, key, pending) -> Any: ...
    def _compute_tool_whitelist_drift(self) -> Any: ...
    def _deliver_llm_reply(self, message, reply_text, history) -> Any: ...
    def _dispatch_reply_send(self, message, reply_title, filtered, reply_uuid) -> Any: ...
    def _enqueue_dead_letter(self, message, *, stage, error) -> Any: ...
    def _ensure_primary(self) -> Any: ...
    def _filter_sensitive_words(self, text) -> Any: ...
    def _handle_media_fallback(self, message) -> Any: ...
    def _handle_message_impl(self, message) -> Any: ...
    def _handle_message_with_rid(self, message, rid) -> Any: ...
    def _handle_oa_approval_urge(self, message) -> Any: ...
    def _handle_rate_limit_exhausted(self, message, exc) -> Any: ...
    def _handle_reply_rate_limited(self, msg_key, exc) -> Any: ...
    def _handle_sensitive_blocked_reply(self, message, reply_text) -> Any: ...
    def _has_replied_after(self, message) -> Any: ...
    def _has_user_taken_over(self, message) -> Any: ...
    def _init_config(self) -> Any: ...
    def _init_primary_components(self) -> Any: ...
    def _init_rules(self) -> Any: ...
    def _init_runtime(self) -> Any: ...
    def _init_scheduler(self) -> Any: ...
    def _init_secondary_platforms(self) -> Any: ...
    def _init_tools_and_llm(self) -> Any: ...
    def _init_user(self) -> Any: ...
    @staticmethod
    def _is_followup_message(content) -> Any: ...
    def _is_incomplete_message(self, message) -> Any: ...
    def _is_internal_confirmation(self, text) -> Any: ...
    def _is_message_from_self(self, message) -> Any: ...
    def _is_oa_approval_message(self, message) -> Any: ...
    def _is_owner_present(self, message) -> Any: ...
    def _reply_gate_reason(self, message) -> Any: ...
    def _should_reply_now(self, message) -> Any: ...
    def _owner_conversation_is_read(self, message) -> Any: ...
    def _unread_conversation_ids(self) -> Any: ...
    def _is_rate_limit_exception(self, exc) -> Any: ...
    @classmethod
    def _is_style_profile_stale(cls, prof, stale_days) -> Any: ...
    def _load_current_user(self) -> Any: ...
    def _make_platform_callback(self, platform_id) -> Any: ...
    def _mark_agent_self_replied(self, message) -> Any: ...
    def _mark_decision_cited(self, message, cited) -> Any: ...
    def _mark_inbound_processed(self, message) -> Any: ...
    def _mark_read_before_reply(self, message) -> Any: ...
    def _mark_reply_sent(self) -> Any: ...
    def _mark_shard_processed(self, result, chat_id) -> Any: ...
    def _merge_platform_title(self, candidate) -> Any: ...
    def _notify_owner_draft(self, message, reply_text) -> Any: ...
    def _oa_approval_is_action(self, message) -> Any: ...
    def _oa_approval_is_question(self, message) -> Any: ...
    def _oa_message_blob(self, message) -> Any: ...
    def _platform_config(self, platform_id) -> Any: ...
    def _prepare_outgoing_text(self, filtered, message) -> Any: ...
    def _process_llm_reply(self, message, result) -> Any: ...
    def _process_pending_messages(self, key) -> Any: ...
    def _rebuild_builtin_tools(self) -> Any: ...
    def _rebuild_kb_search_tool(self) -> Any: ...
    def _record_reply_success(self, message, filtered, reply_uuid, result) -> Any: ...
    def _refresh_style_profile(self) -> Any: ...
    def _refresh_style_profile_worker(self) -> Any: ...
    def _reply_cooldown_active(self, message) -> Any: ...
    def _reply_rate_limited(self) -> Any: ...
    def _reply_send_min_interval(self) -> Any: ...
    def _reply_send_rate_limit_backoff_seconds(self) -> Any: ...
    def _reply_shard_limit(self) -> Any: ...
    def _resolve_own_open_dingtalk_id(self) -> Any: ...
    def _send_possibly_sharded(self, *, chat_id, reply_title, filtered, reply_uuid, **target) -> Any: ...
    def _send_reply(self, message, reply_text) -> Any: ...
    def _send_single_chat_reply(self, message, reply_title, filtered, reply_uuid) -> Any: ...
    def _setup_embedding(self) -> Any: ...
    def _setup_llm(self) -> Any: ...
    def _setup_tools(self) -> Any: ...
    def _should_handoff_low_confidence(self, message, reply_text) -> Any: ...
    def _should_skip_inbound(self, message) -> Any: ...
    def _start_backup_scheduler(self) -> Any: ...
    def _start_conversation_summary_scheduler(self) -> Any: ...
    def _start_decision_cleanup_scheduler(self) -> Any: ...
    def _start_memory_cleanup_scheduler(self) -> Any: ...
    def _start_messages_cleanup_scheduler(self) -> Any: ...
    def _start_global_tables_cleanup_scheduler(self) -> Any: ...
    def _start_wal_checkpoint_scheduler(self) -> Any: ...
    def _scan_orphan_conversation_dbs(self) -> Any: ...
    @staticmethod
    def _style_profile_days_since(prof) -> Any: ...
    def _throttle_reply_send(self) -> Any: ...
    def _track_llm_reply(self, message, result, reply_text) -> Any: ...
    def get_backpressure_metrics(self) -> Any: ...
    def get_debounce_metrics(self) -> Any: ...
    def get_poller_status(self) -> Any: ...
    def get_tool_whitelist_drift(self) -> Any: ...
    def handle_message(self, message) -> Any: ...
    def reload_config(self) -> Any: ...
    def replay_dead_letter(self, dl_id, platform) -> Any: ...
    def run(self, web_port, mode) -> Any: ...
    def shutdown(self, timeout) -> Any: ...
